# Generated by Django 4.0.1 on 2022-01-26 21:26

from django.db import migrations, models
import django.utils.timezone
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_img_1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=products.models.filepath),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_img_2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=products.models.filepath),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_img_3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=products.models.filepath),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_img_4',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=products.models.filepath),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_img_5',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=products.models.filepath),
            preserve_default=False,
        ),
    ]
