# Generated by Django 4.0.1 on 2022-01-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_product_img_1_products_product_img_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='category_id',
        ),
    ]
