# Generated by Django 4.0.1 on 2022-01-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_product_img_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_img_1',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_img_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_img_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_img_4',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_img_5',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
