# Generated by Django 4.0.1 on 2022-01-28 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_product_img_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_img_5',
        ),
    ]
