# Generated by Django 4.0.2 on 2022-02-10 20:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='cartid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.cart'),
            preserve_default=False,
        ),
    ]
