# Generated by Django 4.0.2 on 2022-02-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_mycart_cartid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='mycart',
            name='total_price',
        ),
        migrations.AddField(
            model_name='mycart',
            name='buy_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mycart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
